### ISSUE TITLE
Bitmap View suggestions

### ISSUE THREAD

**Issue by NS-Clone** [rururutan/binaryeditorbz#1]
there is need custom width input 
with slider and arrows on main panel
(for finding sprites for example)
only 128/256 is completely not enough
also requested 1bit and 16bit color modes
and maybe 4bit color mode too
(for 1bit mode maximal width must be at least 2048 pixels (maybe with scroll bar on Y axis (oh it's already implemented)))

for 1bit mode often needs vertical mode
for example
![2024-02-08_024640](https://github.com/rururutan/binaryeditorbz/assets/139008911/b9f53080-ab21-4416-850a-ce863fc42ed8)
![2024-02-08_030930](https://github.com/rururutan/binaryeditorbz/assets/139008911/333ecb46-0ae0-4499-b8cc-c72ff9fe1cc7)
with custom height

2x zoom is completely not enough for 4K monitors

for example raw importer from infanview
with several color modes
![2024-02-08_023826](https://github.com/rururutan/binaryeditorbz/assets/139008911/fd5a038c-702b-480a-8f10-61117ef54f26)

**Comment by NS-Clone** [comment]
looks like i'm in "wrong" issues
can you send it to tamachan's gitlab issues?

**Comment by rururutan** [comment]
Hello.
This repository is a private fork repository.
Please make an issue in tamachan's repository.

I also feel that the bitmap display lacks functionality :-)
